"""other tables

Revision ID: 08d7242d9634
Revises: 2049ae854609
Create Date: 2023-06-01 13:24:16.041322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d7242d9634'
down_revision = '2049ae854609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.create_foreign_key(None, 'admissions', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'admissions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.drop_constraint('adverse_reaction_types_user_id_fkey', 'adverse_reaction_types', type_='foreignkey')
    op.create_foreign_key(None, 'adverse_reaction_types', 'users', ['user_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'adverse_reactions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'allergies', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointment_reminders', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointment_reminders', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'beds', 'patients', ['occupied_by'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'billings', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'chronic_conditions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'departments', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'departments', 'nurses', ['nurse_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'diagnoses', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'diagnoses', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'diseases', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'genetic_conditions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'immunizations', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'insurance_claims', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_results', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_tests', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_conditions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_images', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_notes', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_notes', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_procedures', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_procedures', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medication_alerts', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medication_alerts', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'medications', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_consents', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_feedback', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_feedback', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_visits', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_visits', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'doctors', ['referring_doctor'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'doctors', ['referred_doctor'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'patients', ['referring_patient'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'patients', ['referred_patient'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'specialties', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'vaccinations', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'vital_signs', 'patients', ['patient_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'vital_signs', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'work_schedules', 'doctors', ['doctor_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    op.create_foreign_key(None, 'work_schedules', 'nurses', ['nurse_id'], ['id'], onupdate='NO ACTION', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_schedules', type_='foreignkey')
    op.drop_constraint(None, 'work_schedules', type_='foreignkey')
    op.drop_constraint(None, 'vital_signs', type_='foreignkey')
    op.drop_constraint(None, 'vital_signs', type_='foreignkey')
    op.drop_constraint(None, 'vaccinations', type_='foreignkey')
    op.drop_constraint(None, 'specialties', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.drop_constraint(None, 'patient_feedback', type_='foreignkey')
    op.drop_constraint(None, 'patient_feedback', type_='foreignkey')
    op.drop_constraint(None, 'patient_consents', type_='foreignkey')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_constraint(None, 'medication_alerts', type_='foreignkey')
    op.drop_constraint(None, 'medication_alerts', type_='foreignkey')
    op.drop_constraint(None, 'medical_procedures', type_='foreignkey')
    op.drop_constraint(None, 'medical_procedures', type_='foreignkey')
    op.drop_constraint(None, 'medical_notes', type_='foreignkey')
    op.drop_constraint(None, 'medical_notes', type_='foreignkey')
    op.drop_constraint(None, 'medical_images', type_='foreignkey')
    op.drop_constraint(None, 'medical_conditions', type_='foreignkey')
    op.drop_constraint(None, 'lab_tests', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_constraint(None, 'immunizations', type_='foreignkey')
    op.drop_constraint(None, 'genetic_conditions', type_='foreignkey')
    op.drop_constraint(None, 'diseases', type_='foreignkey')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'chronic_conditions', type_='foreignkey')
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_constraint(None, 'beds', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointment_reminders', type_='foreignkey')
    op.drop_constraint(None, 'appointment_reminders', type_='foreignkey')
    op.drop_constraint(None, 'allergies', type_='foreignkey')
    op.drop_constraint(None, 'adverse_reactions', type_='foreignkey')
    op.drop_constraint(None, 'adverse_reaction_types', type_='foreignkey')
    op.create_foreign_key('adverse_reaction_types_user_id_fkey', 'adverse_reaction_types', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    # ### end Alembic commands ###
